using System;
using Microsoft.EntityFrameworkCore;
using Domain.Entities;
using Domain.Entities.UserModule;
using Domain.Entities.WorkItemModule;
using System.Text.RegularExpressions;

namespace Infrastructure.Persistence;

public class FocusDbContext : DbContext
{
    public DbSet<User> Users => Set<User>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    public DbSet<WorkItem> WorkItems => Set<WorkItem>();
    public DbSet<WorkItemLink> WorkItemLinks => Set<WorkItemLink>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(FocusDbContext).Assembly);

        foreach (var entity in modelBuilder.Model.GetEntityTypes())
        {
            foreach (var property in entity.GetProperties())
            {
                property.SetColumnName(Regex.Replace(property.Name, "([a-z0-9])([A-Z])", "$1_$2").ToLowerInvariant());
                if (property.ClrType == typeof(DateTimeOffset) || property.ClrType == typeof(DateTimeOffset?))
                    property.SetColumnType("timestamp with time zone");
            }

            // IDs are assigned in Domain, not generated by the database.
            modelBuilder.Entity(entity.ClrType).Property(nameof(BaseEntity.Id)).ValueGeneratedNever();
        }
    }

    public FocusDbContext(DbContextOptions<FocusDbContext> options) : base(options)
    {
    }


}
